/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Conexion.conex;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.*;
import com.sun.jdi.connect.spi.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author elhac
 */
public class LLogin extends javax.swing.JFrame {
    
    Registror op = new Registror();
    conex con = new conex();
    Connection cn = (Connection) con.ConectarBd();

    /**
     * Creates new form Login
     */
    public LLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnregistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_nombres = new javax.swing.JTextField();
        tx_apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_documento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tx_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tx_contraseña = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        tx_nroDocumento = new javax.swing.JTextField();
        OBLIGACION = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tx_cargo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Iniciar_sesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_usuario = new javax.swing.JTextField();
        tx_contra = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistro.setText("Registrar usuario");
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });
        jPanel2.add(btnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 88, -1));
        jPanel2.add(tx_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 167, -1));
        jPanel2.add(tx_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 167, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Documento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        tx_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tarjeta de Identidad", "Cedula de Ciudadania" }));
        tx_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_documentoActionPerformed(evt);
            }
        });
        jPanel2.add(tx_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 167, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));
        jPanel2.add(tx_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 167, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Crear Contraseña:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        tx_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_contraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(tx_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 167, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" N° de Documento:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel2.add(tx_nroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 167, -1));

        OBLIGACION.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        OBLIGACION.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(OBLIGACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 376, 349, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cargo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        tx_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Usuario", "Administrador" }));
        jPanel2.add(tx_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 167, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/balcon.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        jTabbedPane1.addTab("Agregar Usuarios", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 140, 130));

        Iniciar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Iniciar_sesion.setText("Iniciar sesiòn");
        Iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(Iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 36));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, -1));

        tx_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(tx_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 140, -1));
        jPanel1.add(tx_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 282, 140, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 12, 60, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 290, 10));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 290, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pool.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        jTabbedPane1.addTab("Login", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_sesionActionPerformed

        String usuario = tx_usuario.getText();
        String passw = tx_contra.getText();
        if (!usuario.equals("") || !passw.equals("")) {
            try {
                PreparedStatement ps = (PreparedStatement) cn.prepareStatement("SELECT cargo from usuarios WHERE Email='" + usuario + "' and Contraseña='" + passw + "'");

                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String cargo = rs.getString("cargo");
                    if (cargo.equalsIgnoreCase("Usuario")) {

                new principal().setVisible(true);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "USUARIO Y/O CONTRASEÑA INCORRECTOS");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "NO SE PUEDE INICIAR SECCION");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Por favor, ingresar los datos");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Iniciar_sesionActionPerformed

    private void tx_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_usuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        String nombres = tx_nombres.getText();
        String apellidos = tx_apellidos.getText();
        String tipoDocumento = tx_documento.getSelectedItem().toString();
        String nrodocumento = tx_nroDocumento.getText();
        String Email = tx_email.getText();
        String cargo = tx_cargo.getSelectedItem().toString();
        String Contraseña = tx_contraseña.getText();

        op.registro(nombres, apellidos, tipoDocumento,nrodocumento, Email, cargo, Contraseña,  OBLIGACION);

        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistroActionPerformed

    private void tx_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_documentoActionPerformed

    private void tx_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar_sesion;
    private javax.swing.JLabel OBLIGACION;
    private javax.swing.JButton btnregistro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tx_apellidos;
    private javax.swing.JComboBox<String> tx_cargo;
    private javax.swing.JTextField tx_contra;
    private javax.swing.JPasswordField tx_contraseña;
    private javax.swing.JComboBox<String> tx_documento;
    private javax.swing.JTextField tx_email;
    private javax.swing.JTextField tx_nombres;
    private javax.swing.JTextField tx_nroDocumento;
    private javax.swing.JTextField tx_usuario;
    // End of variables declaration//GEN-END:variables
void limpiar() {
        tx_nombres.setText("");
        tx_apellidos.setText("");
        tx_documento.getSelectedItem().toString();
        tx_nroDocumento.setText("");
        tx_email.setText("");
        tx_contraseña.setText("");
    }
}
